management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

  info:
    java:
      enabled: true

    os:
      enabled: true

server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transaction-id-prefix: orders-tx

    consumer:
      group-id: orders

orders:
  events:
    topic:
      name: orders.order-created-event
      fail: orders.orders-creation-failed-event

  dead-letter-topic:
    name: orders.dead-letter-topic

foods:
  events:
    topic:
      fail: foods.order-creation-failed-event

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3


logging:
  level:
    org:
      apache:
#        kafka: TRACE
        orm:
          jpa:
            JpaTransactionManager: TRACE
      hibernate.sql: TRACE

---

spring:
  config:
    activate:
      on-profile: prod

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_IP}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

  info:
    java:
      enabled: true

    os:
      enabled: true

  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          base-url: ${MONITORING_SERVER_IP}
          push-rate: 30s
          job: orders-service
        enabled: true

server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true