spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_IP}
    producer:
      transaction-id-prefix: orders-tx

    consumer:
      group-id: orders

orders:
  events:
    topic:
      name: orders.order-created-event
      fail: orders.orders-creation-failed-event

  dead-letter-topic:
    name: orders.dead-letter-topic

foods:
  events:
    topic:
      fail: foods.order-creation-failed-event

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3


logging:
  level:
    org:
      apache:
#        kafka: TRACE
        zorm:
          jpa:
            JpaTransactionManager: TRACE
      hibernate.sql: TRACE
