management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

  info:
    java:
      enabled: true

    os:
      enabled: true

server:
  port: 8084
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: foods

  jpa:
    properties:
      hibernate:
        show_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transaction-id-prefix: foods-tx

    consumer:
      group-id: foods

orders:
  events:
    topic:
      name: orders.order-created-event

foods:
  events:
    topic:
      name: foods.order-created-event
      fail: foods.order-creation-failed-event

  dead-letter-topic:
    name: foods.dead-letter-topic

payments:
  events:
    topic:
      fail: payments.order-creation-failed-event

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3

logging:
  level:
    org.hibernate.sql: TRACE
#
#    org.springframework.kafka: TRACE
#    org.apache.kafka: TRACE

---

spring:
  config:
    activate:
      on-profile: prod

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_IP}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

  info:
    java:
      enabled: true

    os:
      enabled: true

  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          base-url: ${MONITORING_SERVER_IP}
          push-rate: 30s
          job: foods-service
        enabled: true

server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true
