server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transaction-id-prefix: foods-tx

    consumer:
      group-id: foods

  datasource:
    url: jdbc:mysql://joyeuse-planete-db.cpmeiucaside.eu-west-2.rds.amazonaws.com:3306/JOYEUSE_PLANETE_TEST
    username: gunho
    password: drafix0513
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect

orders:
  events:
    topics:
      create: orders.order-created-event
      cancel: orders.order-cancellation-event
      create-fail: orders.orders-creation-failed-event

  dead-letter-topic: orders.dead-letter-topic

foods:
  events:
    topics:
      reserve: foods.food-reserved-event
      reserve-fail: foods.food-reservation-failed-event
      release: foods.food-release-event
      release-fail: foods.food-release-fail-event

  dead-letter-topic: foods.dead-letter-topic


payment:
  events:
    topics:
      process: payment.payment-processed-event
      process-fail: payment.payment-processing-fail-event

  dead-letter-topic: payment.dead-letter-topic

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3

logging:
  level:
    org.hibernate.sql: TRACE