spring:
  application:
    name: payments

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_IP}
    producer:
      transaction-id-prefix: payments-tx

    consumer:
      group-id: payments

payments:
  events:
    topic:
      name: payments.order-creation-event
      fail: payments.order-creation-failed-event

  dead-letter-topic:
    name: payments.dead-letter-topic

foods:
  events:
    topic:
      name: foods.order-created-event

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3