
---

spring:
  config:
    activate:
      on-profile: prod

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_IP}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, bean"

  info:
    java:
      enabled: true

    os:
      enabled: true

  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          base-url: ${MONITORING_SERVER_IP}
          push-rate: 30s
          job: notifications-service
        enabled: true


server:
  port: 8080
